#layout Configuration.
UNI.NOTE.LAYOUT.PATH.LAYOUT=layouts
UNI.NOTE.LAYOUT.HTML.PATH.MAIN=main_files
UNI.NOTE.LAYOUT.TEMPLATE.MAIN=main.template
UNI.NOTE.LAYOUT.TEMPLATE.MD=md.template
UNI.NOTE.LAYOUT.TEMPLATE.TOC=toc.template
UNI.NOTE.FORMAT.MAIN.WIDTH=1000
#note Configuration
UNI.NOTE.NEW.MD.TEMPLATE=new_note.template.md